#pragma config(Sensor, S2,     HTSMUX,              sensorI2CCustom)
#pragma config(Sensor, S3,     accel,               sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "HTSMUX-driver.h"
#include "HTAC-driver.h"

#define accel msensor_s2_2

task main()
{
  int sum;
  float ax,ay,az;
  int dt,st,en;
  dt=10;

  float sumx,sumy,sumz;
  ClearTimer(T1);
  time1(T1)=st;
  HTACreadAllAxes(accel,ax,ay,az);
  sumx+=ax*(dt/1000)*(dt/1000);
  sumy+=ay*(dt/1000)*(dt/1000);
  sumz+=az*(dt/1000)*(dt/1000);
  nxtDisplayTextLine(1,"%f",sumx);
  nxtDisplayTextLine(2,"%f",sumy);
  nxtDisplayTextLine(3,"%f",sumz);
  time1(T1)=en;
  dt=en-st;
  while(true)
  {
    HTACreadAllAxes(accel,ax,ay,az);
    sumx+=ax*(dt/1000)*(dt/1000);
    sumy+=ay*(dt/1000)*(dt/1000);
    sumz+=az*(dt/1000)*(dt/1000);
    nxtDisplayTextLine(1,"%f",sumx);
    nxtDisplayTextLine(2,"%f",sumy);
    nxtDisplayTextLine(3,"%f",sumz);
  }
}
